begin;

create extension if not exists pgtap;
select plan(12);

select has_table('qarar_governance','governance_bundles_v2','V2 bundle aggregate exists');
select has_table('qarar_governance','governance_bundle_reviews_v2','V2 review history exists');
select has_table('qarar_governance','governance_bundle_command_receipts_v2','V2 command receipts exist');

select is(
  (select count(*)::integer from qarar_architecture.entity_registry
   where entity_name in ('governance_bundles_v2','governance_bundle_reviews_v2','governance_bundle_command_receipts_v2')
     and module_code='governance'),
  3,
  'all bundle entities are registered to governance'
);

select is(
  (select count(*)::integer from pg_class c join pg_namespace n on n.oid=c.relnamespace
   where n.nspname='qarar_governance'
     and c.relname in ('governance_bundles_v2','governance_bundle_reviews_v2','governance_bundle_command_receipts_v2')
     and c.relrowsecurity and c.relforcerowsecurity),
  3,
  'all bundle entities enforce RLS'
);

select is(
  (select count(*)::integer from information_schema.role_table_grants
   where table_schema='qarar_governance'
     and table_name in ('governance_bundles_v2','governance_bundle_reviews_v2','governance_bundle_command_receipts_v2')
     and grantee in ('anon','authenticated','service_role')),
  0,
  'API roles have no direct bundle table grants'
);

select col_default_is(
  'qarar_governance','governance_bundles_v2','reference_number',
  'qarar_governance.next_v2_reference(''GVB''::text)',
  'bundle reference is generated by the database'
);

select col_default_is(
  'qarar_governance','governance_bundles_v2','status',
  'draft',
  'new bundle starts as draft'
);

select col_default_is(
  'qarar_governance','governance_bundles_v2','lock_version',
  '1',
  'bundle conflict version starts at one'
);

select ok(
  exists(select 1 from pg_constraint
         where conrelid='qarar_governance.governance_bundles_v2'::regclass
           and conname='governance_bundles_v2_activation_blocked'),
  'foundation explicitly blocks activation'
);

select ok(
  not has_table_privilege('qarar_governance_executor','qarar_governance.governance_bundle_reviews_v2','UPDATE,DELETE'),
  'review history is append only'
);

select ok(
  not has_table_privilege('qarar_governance_executor','qarar_governance.governance_bundle_command_receipts_v2','UPDATE,DELETE'),
  'command receipts are append only'
);

select * from finish();
rollback;
