begin;
create extension if not exists pgtap;
select no_plan();
select has_function('api_v2','admin_save_regulation_library_v2',array['uuid','text','jsonb','text','uuid'],'atomic library command is installed');
insert into qarar_core.organizations(id,code,name_ar) values
 ('69000000-0000-0000-0000-000000000001','library-test','اختبار مكتبة اللوائح'),
 ('69000000-0000-0000-0000-000000000002','library-other','مؤسسة أخرى');
insert into auth.users(id,email) values
 ('69000000-0000-0000-0000-000000000010','library-admin@example.test'),
 ('69000000-0000-0000-0000-000000000011','library-review@example.test'),
 ('69000000-0000-0000-0000-000000000012','library-denied@example.test'),
 ('69000000-0000-0000-0000-000000000013','library-other@example.test');
insert into qarar_iam.users(id,organization_id,email,full_name_ar,is_system_admin) values
 ('69000000-0000-0000-0000-000000000010','69000000-0000-0000-0000-000000000001','library-admin@example.test','محرر',true),
 ('69000000-0000-0000-0000-000000000011','69000000-0000-0000-0000-000000000001','library-review@example.test','مراجع',true),
 ('69000000-0000-0000-0000-000000000012','69000000-0000-0000-0000-000000000001','library-denied@example.test','غير مخول',false),
 ('69000000-0000-0000-0000-000000000013','69000000-0000-0000-0000-000000000002','library-other@example.test','مؤسسة أخرى',true);
create function pg_temp.actor(p_id uuid) returns void language plpgsql as $$ begin
 perform set_config('request.jwt.claim.sub',p_id::text,true);
 perform set_config('request.jwt.claims',jsonb_build_object('sub',p_id,'role','authenticated','aal','aal2')::text,true);
end $$;
select pg_temp.actor('69000000-0000-0000-0000-000000000010');
create temporary table results(name text primary key,data jsonb);
insert into results values ('created',api_v2.admin_save_regulation_library_v2(null,'create','{"name_ar":"لائحة أكاديمية جديدة"}',null,'69000000-0000-0000-0000-000000000020'));
create function pg_temp.policy_id() returns uuid language sql as $$ select (data->'policy'->>'id')::uuid from results where name='created' $$;
create function pg_temp.version_id() returns uuid language sql as $$ select (data->>'selected_version_id')::uuid from results where name='created' $$;
create function pg_temp.command(p_action text,p_payload jsonb default '{}') returns jsonb language sql as $$
 select api_v2.admin_save_regulation_library_v2(pg_temp.policy_id(),p_action,p_payload,
   api_v2.admin_get_regulation_library_v2(pg_temp.policy_id())->>'revision',gen_random_uuid())
$$;
select matches((select data->'policy'->>'reference_number' from results where name='created'),'^REG-[0-9]{4}-[0-9]{6}$','reference generated by database');
select is((select jsonb_array_length(data->'policy'->'versions') from results where name='created'),1,'first draft created atomically');
select is((select data->'policy'->'versions'->0->>'legal_status' from results where name='created'),'draft','new record is a draft, not effective');
select lives_ok($$select api_v2.admin_save_regulation_library_v2(null,'create','{"name_ar":"لائحة أكاديمية جديدة"}',null,'69000000-0000-0000-0000-000000000020')$$,'replay of create succeeds');
select is((select count(*)::integer from qarar_governance.policies where organization_id='69000000-0000-0000-0000-000000000001'),1,'replay does not duplicate policy');
select throws_ok($$select api_v2.admin_save_regulation_library_v2(null,'create','{"name_ar":"اسم مختلف"}',null,'69000000-0000-0000-0000-000000000020')$$,'22023',null,'request id cannot be reused with different contents');
select throws_ok($$select pg_temp.command('save_identity','{"name_ar":"صحيح","code":"manual"}')$$,'22023',null,'manual identifiers rejected');
select throws_ok($$select api_v2.admin_save_regulation_library_v2(pg_temp.policy_id(),'save_identity','{"name_ar":"اسم جديد"}','stale',gen_random_uuid())$$,'PT409',null,'business conflict uses terminal HTTP conflict, not a retryable serialization failure');
select throws_ok($$select pg_temp.command('submit',jsonb_build_object('version_id',pg_temp.version_id()))$$,'23514',null,'empty legal source cannot be submitted');
select is((select legal_status from qarar_governance.policy_versions where id=pg_temp.version_id()),'draft','failed submission leaves draft unchanged');
insert into results values ('item',pg_temp.command('save_item',jsonb_build_object('version_id',pg_temp.version_id(),'title_ar','قبول الطلاب','body_text','نص المادة الأصلي','item_type','article')));
select matches((select data->'policy'->'versions'->0->'items'->0->>'item_code' from results where name='item'),'^ART-[0-9]{4}-[0-9]{6}$','item reference generated');
select throws_ok($$select pg_temp.command('save_item',jsonb_build_object('version_id',pg_temp.version_id(),'title_ar','عنوان صحيح','body_text','نص','parent_item_id','69000000-0000-0000-0000-000000000099'))$$,'22023',null,'invalid parent rejected');
select is((select count(*)::integer from qarar_governance.policy_items where policy_version_id=pg_temp.version_id()),1,'failed save leaves no partial item');
select lives_ok($$select pg_temp.command('save_item',jsonb_build_object('version_id',pg_temp.version_id(),'item_id',(select data->>'item_id' from results where name='item'),'title_ar','قبول الطلاب','body_text','النص بعد التعديل','item_type','article','source_locator','المادة الأولى'))$$,'legal text and source saved together');
select is((select official_text from qarar_governance.policy_items where policy_version_id=pg_temp.version_id()),'النص بعد التعديل','updated legal text persisted');
select throws_ok($$select pg_temp.command('save_item',jsonb_build_object('version_id',pg_temp.version_id(),'item_id',(select data->>'item_id' from results where name='item'),'title_ar','محاولة فاشلة','body_text','نص يجب ألا يحفظ','item_type','article','source_page_from',5,'source_page_to',3))$$,'22023',null,'bad source range rolls back text update too');
select is((select official_text from qarar_governance.policy_items where policy_version_id=pg_temp.version_id()),'النص بعد التعديل','no partially saved text after source failure');
select pg_temp.actor('69000000-0000-0000-0000-000000000012');
select throws_ok($$select api_v2.admin_get_regulation_library_v2(pg_temp.policy_id())$$,'42501',null,'unauthorized read denied');
select throws_ok($$select pg_temp.command('begin_edit')$$,'42501',null,'unauthorized write denied');
select pg_temp.actor('69000000-0000-0000-0000-000000000013');
select throws_ok($$select api_v2.admin_get_regulation_library_v2(pg_temp.policy_id())$$,'P0002',null,'other organization cannot read');
select pg_temp.actor('69000000-0000-0000-0000-000000000010');
select lives_ok($$select pg_temp.command('submit',jsonb_build_object('version_id',pg_temp.version_id()))$$,'legal source submitted without a workflow');
select throws_ok($$select pg_temp.command('approve',jsonb_build_object('version_id',pg_temp.version_id()))$$,'42501',null,'submitter cannot approve own submission');
select throws_ok($$select pg_temp.command('save_item',jsonb_build_object('version_id',pg_temp.version_id(),'title_ar','ممنوع','body_text','نص','item_type','article'))$$,'55000',null,'under-review text protected');
select pg_temp.actor('69000000-0000-0000-0000-000000000011');
select lives_ok($$select pg_temp.command('return',jsonb_build_object('version_id',pg_temp.version_id(),'reason','استكمال المرجع'))$$,'independent reviewer can return draft');
select is((select legal_status from qarar_governance.policy_versions where id=pg_temp.version_id()),'draft','returned text can be corrected');
select pg_temp.actor('69000000-0000-0000-0000-000000000010');
select lives_ok($$select pg_temp.command('submit',jsonb_build_object('version_id',pg_temp.version_id()))$$,'returned draft can be submitted again');
select pg_temp.actor('69000000-0000-0000-0000-000000000011');
select lives_ok($$select pg_temp.command('approve',jsonb_build_object('version_id',pg_temp.version_id()))$$,'independent approver accepted');
select lives_ok($$select pg_temp.command('activate',jsonb_build_object('version_id',pg_temp.version_id()))$$,'legal source activated without pretending automation is ready');
select is((select automation_status from qarar_governance.policy_versions where id=pg_temp.version_id()),'not_configured','source activation does not enable legacy automation');
insert into results values ('edit',pg_temp.command('begin_edit'));
select is((select jsonb_array_length(data->'policy'->'versions') from results where name='edit'),2,'edit creates a new internal draft');
select is((select data->'policy'->'versions'->0->'items'->0->>'official_text' from results where name='edit'),'النص بعد التعديل','new draft inherits items');
select is((select legal_status from qarar_governance.policy_versions where id=pg_temp.version_id()),'effective','old text stays effective until next approval');
select lives_ok($$select pg_temp.command('begin_edit')$$,'reopening existing draft succeeds');
select is((select count(*)::integer from qarar_governance.policy_versions where policy_id=pg_temp.policy_id()),2,'reopening does not create more drafts');
select lives_ok($$select pg_temp.command('set_status','{"status":"archived"}')$$,'archive preserves regulation');
select throws_ok($$select pg_temp.command('begin_edit')$$,'55000',null,'archived regulation cannot be edited');
select is((select count(*)::integer from qarar_governance.policy_versions where policy_id=pg_temp.policy_id()),2,'archive preserves history');
select lives_ok($$select pg_temp.command('set_status','{"status":"active"}')$$,'archived regulation can be restored');
select ok(not has_function_privilege('anon','api_v2.admin_save_regulation_library_v2(uuid,text,jsonb,text,uuid)','execute'),'anonymous command execution denied');
select ok(not has_table_privilege('authenticated','qarar_governance.regulation_library_commands_v2','insert'),'clients cannot forge receipts');
-- Existing authoring records remain intact; the simplified journey must create
-- a source-only working copy, not silently change a legacy process.
insert into results values ('legacy',qarar_governance.admin_create_policy_idempotent('legacy-library','لائحة قديمة',null,'regulation',null,null,gen_random_uuid()));
insert into results values ('legacy_version',qarar_governance.admin_create_policy_version((select (data->>'id')::uuid from results where name='legacy'),null,null));
select qarar_governance.admin_add_policy_item(p_policy_version_id=>(select (data->>'id')::uuid from results where name='legacy_version'),p_item_code=>'old-item',p_title_ar=>'بند قديم',p_sort_order=>1,p_item_type=>'article',p_body_text=>'النص القديم');
insert into results values ('legacy_edit',api_v2.admin_save_regulation_library_v2((select (data->>'id')::uuid from results where name='legacy'),'begin_edit','{}',api_v2.admin_get_regulation_library_v2((select (data->>'id')::uuid from results where name='legacy'))->>'revision',gen_random_uuid()));
select is((select data->'policy'->'versions'->0->>'library_mode' from results where name='legacy_edit'),'true','legacy drafts get a new source-only working copy');
select is((select count(*)::integer from qarar_governance.policy_versions where policy_id=(select (data->>'id')::uuid from results where name='legacy')),2,'legacy version preserved alongside new draft');
select is((select coalesce(data->'policy'->'versions'->0->'items'->0->>'official_text',data->'policy'->'versions'->0->'items'->0->>'body_text') from results where name='legacy_edit'),'النص القديم','legacy text inherited into simplified authoring');
select is((select library_mode from qarar_governance.policy_versions where id=(select (data->>'id')::uuid from results where name='legacy_version')),false,'old process not converted in place');
select throws_ok($$select pg_temp.command('save_item',jsonb_build_object('version_id',(select data->>'selected_version_id' from results where name='edit'),'title_ar','عنوان صحيح','body_text','نص','item_type','article','source_page_to',3))$$,'22023',null,'source page end without start rejected atomically');
select * from finish();
rollback;
