export type PolicyItem = {
  id: string;
  policy_version_id: string;
  item_code: string;
  item_type: string;
  title_ar: string;
  title_en?: string | null;
  body_text?: string | null;
  sort_order: number;
  parent_item_id?: string | null;
  governance_mode: string;
  topic_category_id?: string | null;
  match_criteria: Record<string, unknown>;
  workflow_template_version_id?: string | null;
  is_active: boolean;
  attachments?: PolicyAttachment[];
  official_text?: string | null;
  interpretation_text?: string | null;
  source_page_from?: number | null;
  source_page_to?: number | null;
  source_locator?: string | null;
  legal_status?: "active" | "amended" | "repealed" | "suspended";
  amendment_note?: string | null;
  requires_executable_rule?: boolean;
  supersedes_item_id?: string | null;
  rules?: PolicyRule[];
  references?: PolicyReference[];
};
export type PolicyScope = {
  id: string;
  policy_version_id: string;
  scope_type: string;
  target_id?: string | null;
  governance_level?: string | null;
  include_descendants: boolean;
  priority: number;
  valid_from?: string | null;
  valid_to?: string | null;
  is_active: boolean;
};
export type PolicyVersion = {
  id: string;
  version_no: number;
  version_label?: string | null;
  legal_status: string;
  automation_status: string;
  readiness_percent?: number;
  /** @deprecated Compatibility with responses produced before PB-060. */
  automation_readiness_pct?: number;
  effective_from?: string | null;
  effective_to?: string | null;
  change_summary?: string | null;
  items: PolicyItem[];
  scopes: PolicyScope[];
  submitted_at?: string | null;
  approved_at?: string | null;
  submitted_by_user_id?: string | null;
  approved_by_user_id?: string | null;
  activated_by_user_id?: string | null;
  activated_at?: string | null;
  attachments?: PolicyAttachment[];
  issuing_authority?: string | null;
  approval_authority?: string | null;
  approval_decision_number?: string | null;
  approval_date?: string | null;
  issue_reason?: string | null;
  supersedes_version_id?: string | null;
  source_document_hash?: string | null;
};
export type PolicyAttachment = {
  id: string;
  file_name: string;
  file_url: string;
  mime_type?: string | null;
  file_size_bytes?: number | null;
  description?: string | null;
  created_at: string;
};
export type RuleCondition = {
  id?: string;
  condition_code: string;
  field_path: string;
  operator: string;
  expected_value: unknown;
  failure_action: string;
  failure_message_ar?: string | null;
  sequence_no?: number;
};
export type RuleRequirement = {
  id?: string;
  requirement_code: string;
  name_ar: string;
  requirement_type: string;
  is_mandatory: boolean;
  timing: string;
  validation_spec: Record<string, unknown>;
  sequence_no?: number;
};
export type RuleAuthority = {
  id?: string;
  governance_unit_id?: string | null;
  governance_class_id?: string | null;
  responsibility: string;
  authority_action: string;
  required_permission_code?: string | null;
  is_final: boolean;
  sequence_no?: number;
};
export type RuleAction = {
  id?: string;
  action_code: string;
  label_ar: string;
  action_type: string;
  is_terminal: boolean;
  requires_reason: boolean;
  result_payload: Record<string, unknown>;
  sequence_no?: number;
};
export type RuleWorkflowBinding = {
  id?: string;
  workflow_template_version_id: string;
  binding_type: "primary" | "objection" | "exception" | "fallback";
  selection_conditions: Record<string, unknown>;
  priority: number;
};
export type PolicyRule = {
  id: string;
  policy_item_id: string;
  rule_code: string;
  name_ar: string;
  description?: string | null;
  rule_type: string;
  status: string;
  priority: number;
  applies_when: Record<string, unknown>;
  effect_payload: Record<string, unknown>;
  requires_workflow: boolean;
  valid_from?: string | null;
  valid_to?: string | null;
  conditions: RuleCondition[];
  requirements: RuleRequirement[];
  authorities: RuleAuthority[];
  actions: RuleAction[];
  workflow_bindings: RuleWorkflowBinding[];
};
export type PolicyReference = {
  id: string;
  source_policy_item_id: string;
  target_policy_id?: string | null;
  target_policy_version_id?: string | null;
  target_policy_item_id?: string | null;
  external_reference?: string | null;
  reference_type: string;
  citation_text?: string | null;
  notes?: string | null;
};
export type LegislativeReadiness = {
  ready: boolean;
  score: number;
  errors: Array<{ code: string; message: string }>;
  warnings: Array<{ code: string; message: string }>;
  items_total: number;
  items_ready: number;
};
export type PolicyVersionComparison = {
  added: PolicyItem[];
  removed: PolicyItem[];
  modified: Array<{ item_code: string; left: PolicyItem; right: PolicyItem }>;
};
export type Policy = {
  id: string;
  code: string;
  name_ar: string;
  name_en?: string | null;
  policy_type: string;
  status: string;
  description?: string | null;
  owner_user_id?: string | null;
  owner_governance_unit_id?: string | null;
  legal_reference?: string | null;
  decision_number?: string | null;
  attachments?: PolicyAttachment[];
  updated_at: string;
  version_count?: number;
  latest_version_no?: number;
  versions?: PolicyVersion[];
};
export type WorkflowStep = {
  id: string;
  workflow_template_version_id: string;
  step_code: string;
  name_ar: string;
  sequence_no: number;
  step_type: string;
  responsibility: string;
  governance_unit_id?: string | null;
  governance_class_id?: string | null;
  required_permission_code?: string | null;
  is_initial: boolean;
  is_terminal: boolean;
  allowed_outcomes: string[];
};
export type WorkflowTransition = {
  id: string;
  from_step_id: string;
  to_step_id?: string | null;
  outcome_code: string;
  transition_type: string;
};
export type WorkflowVersion = {
  id: string;
  version_no: number;
  status: string;
  validation_status: string;
  steps: WorkflowStep[];
  transitions: WorkflowTransition[];
};
export type WorkflowTemplate = {
  id: string;
  code: string;
  name_ar: string;
  name_en?: string | null;
  description?: string | null;
  status: string;
  versions: WorkflowVersion[];
};
export type ReferenceOption = {
  id: string;
  code: string;
  name_ar: string;
  [key: string]: unknown;
};
export type GovernanceException = {
  id: string;
  topic_id: string;
  topic_title_ar: string;
  exception_type: string;
  status: string;
  reason: string;
  valid_until: string;
  requested_at: string;
  workflow_name_ar?: string | null;
};
