"use client";
import { useEffect, useRef, useState } from "react";
import { Check, KeyRound, ShieldCheck } from "lucide-react";
import { FormField } from "@/shared/ui/form-field";
import { FullLogo } from "@/shared/ui/logo";

type Invitation={email:string;full_name_ar:string;organization_name:string;expires_at:string};
function takeToken(){const token=new URLSearchParams(location.hash.slice(1)).get("token")??"";if(token)history.replaceState(null,"",location.pathname);return token;}
export function ActivationForm(){
 const tokenRef=useRef("");const[invitation,setInvitation]=useState<Invitation|null>(null);const[password,setPassword]=useState("");const[confirmation,setConfirmation]=useState("");const[status,setStatus]=useState<"loading"|"ready"|"submitting"|"success"|"invalid">("loading");const[message,setMessage]=useState("");
 useEffect(()=>{const value=tokenRef.current||takeToken();tokenRef.current=value;if(!value){queueMicrotask(()=>setStatus("invalid"));return;}const controller=new AbortController();void fetch("/api/auth/activate",{headers:{"X-Qarar-Activation-Token":value},cache:"no-store",signal:controller.signal}).then(async response=>{const result=await response.json().catch(()=>({}));if(!response.ok)throw new Error(result?.error?.message??"رابط التفعيل غير صالح.");setInvitation(result.invitation);setStatus("ready");}).catch((error:unknown)=>{if((error as {name?:string})?.name!=="AbortError"){setMessage(error instanceof Error?error.message:"رابط التفعيل غير صالح.");setStatus("invalid");}});return()=>controller.abort();},[]);
 async function submit(event:React.FormEvent){event.preventDefault();setMessage("");if(password!==confirmation){setMessage("كلمتا المرور غير متطابقتين.");return;}setStatus("submitting");try{const response=await fetch("/api/auth/activate",{method:"POST",headers:{"Content-Type":"application/json","X-Qarar-Activation-Token":tokenRef.current},body:JSON.stringify({password}),cache:"no-store"});const result=await response.json().catch(()=>({}));if(!response.ok)throw new Error(result?.error?.message??"تعذر تفعيل الحساب.");setPassword("");setConfirmation("");setStatus("success");}catch(error){setMessage(error instanceof Error?error.message:"تعذر تفعيل الحساب.");setStatus("ready");}}
 return <main className="soft-grid flex min-h-screen items-center justify-center px-6 py-10"><div className="w-full max-w-[460px] rounded-3xl border border-[#e1e8f0] bg-white p-7 shadow-xl sm:p-9"><FullLogo/>
 {status==="loading"&&<p className="mt-9 text-sm text-[#6c7d91]">جارٍ التحقق من الدعوة الآمنة…</p>}
 {status==="invalid"&&<div className="mt-9"><h1 className="text-2xl font-black text-[#0a1330]">تعذر استخدام الدعوة</h1><p role="alert" className="mt-3 text-sm leading-7 text-red-700">{message||"الرابط مفقود أو منتهي أو استُخدم سابقًا."}</p></div>}
 {status==="success"&&<div className="mt-9"><span className="grid h-12 w-12 place-items-center rounded-full bg-[#e9f8f1] text-[#16835f]"><Check/></span><h1 className="mt-5 text-2xl font-black text-[#0a1330]">تم تفعيل الحساب</h1><p className="mt-3 text-sm text-[#6c7d91]">يمكنك الآن تسجيل الدخول بكلمة المرور الجديدة.</p><a href="/login" className="mt-6 block rounded-xl bg-[#0066cc] px-4 py-3 text-center text-sm font-bold text-white">الانتقال إلى تسجيل الدخول</a></div>}
 {(status==="ready"||status==="submitting")&&invitation&&<><div className="mt-8"><span className="inline-flex items-center gap-2 rounded-full bg-[#e9f8f1] px-3 py-1.5 text-[10px] font-bold text-[#16835f]"><Check size={13}/>تم التحقق من الدعوة</span><h1 className="mt-4 text-3xl font-black text-[#0a1330]">تفعيل حسابك</h1><p className="mt-3 text-sm text-[#6c7d91]">مرحبًا {invitation.full_name_ar||"بك"} — {invitation.organization_name}</p></div><form onSubmit={submit} className="mt-7 space-y-5"><div className="rounded-xl border border-[#dfe7ef] px-4 py-3"><p className="text-[10px] text-[#8a99ac]">البريد المؤسسي</p><p className="mt-1 text-xs font-bold" dir="ltr">{invitation.email}</p></div><FormField label="كلمة المرور الجديدة" type="password" autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)} icon={<KeyRound size={17}/>} required/><FormField label="تأكيد كلمة المرور" type="password" autoComplete="new-password" value={confirmation} onChange={e=>setConfirmation(e.target.value)} icon={<KeyRound size={17}/>} required/><p className="text-[10px] leading-5 text-[#64758a]">12 محرفًا على الأقل، وحرف كبير وصغير ورقم ورمز خاص.</p>{message&&<p role="alert" className="rounded-xl bg-red-50 p-3 text-xs text-red-700">{message}</p>}<button disabled={status==="submitting"} className="h-12 w-full rounded-xl bg-[#0066cc] text-sm font-bold text-white disabled:opacity-60">{status==="submitting"?"جارٍ التفعيل…":"تفعيل الحساب"}</button></form><div className="mt-6 flex gap-2 rounded-xl bg-[#f0f6fc] p-3 text-[10px] leading-5 text-[#5d7087]"><ShieldCheck size={15} className="shrink-0 text-[#0066cc]"/>الرابط أحادي الاستخدام، ولا تُرسل كلمة المرور أو الرمز إلى أي نطاق خارجي.</div></>}
 </div></main>;
}
