"use client";
import { useCallback, useEffect, useState } from "react";

type RequestItem = { id:string; type?:string; target_user_id?:string; successor_user_id?:string; justification:string; requested_by_user_id:string; correlation_id?:string; created_at:string };
type Queue = { iam_changes:RequestItem[]; offboarding:RequestItem[] };
export function ApprovalRequestsWorkspace() {
  const [queue,setQueue]=useState<Queue>({iam_changes:[],offboarding:[]}); const [error,setError]=useState(""); const [busy,setBusy]=useState("");
  const load=useCallback(async()=>{try{const r=await fetch("/api/admin/iam",{cache:"no-store"});const v=await r.json();if(!r.ok)throw new Error(v.message);setQueue(v);}catch(e){setError(e instanceof Error?e.message:"تعذر التحميل");}},[]);
  useEffect(()=>{queueMicrotask(() => void load());},[load]);
  async function decide(kind:"iam"|"offboarding",id:string,decision:"approved"|"rejected") { setBusy(id);setError("");try{const r=await fetch("/api/admin/iam",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({operation:kind==="iam"?"reviewIamChange":"reviewOffboarding",payload:{p_request_id:id,p_decision:decision,p_notes:"Reviewed from approval queue"}})});const v=await r.json();if(!r.ok)throw new Error(v.message);await load();}catch(e){setError(e instanceof Error?e.message:"تعذر تنفيذ القرار");}finally{setBusy("");}}
  const cards=[...queue.iam_changes.map(v=>({kind:"iam" as const,item:v,title:"تغيير صلاحيات حساس"})),...queue.offboarding.map(v=>({kind:"offboarding" as const,item:v,title:"مغادرة مستخدم"}))];
  return <main className="mx-auto max-w-5xl"><h1 className="text-2xl font-black">طلبات الاعتماد المزدوج</h1><p className="mt-2 text-sm text-slate-600">لا يستطيع مقدم الطلب اعتماد طلبه. التطبيق يتم داخل المعاملة بعد موافقة مسؤول آخر.</p>{error&&<p role="alert" className="mt-4 rounded-xl bg-red-50 p-3 text-red-700">{error}</p>}<div className="mt-6 space-y-4">{cards.length===0?<div className="rounded-2xl border bg-white p-8 text-center text-sm text-slate-500">لا توجد طلبات معلقة.</div>:cards.map(({kind,item,title})=><article key={item.id} className="rounded-2xl border bg-white p-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="font-black">{title}</h2><p className="mt-2 text-sm text-slate-600">{item.justification}</p><p className="mt-2 text-xs text-slate-400">الطالب: {item.requested_by_user_id}{item.target_user_id&&` · المستخدم: ${item.target_user_id}`}</p>{item.correlation_id&&<p className="mt-1 font-mono text-[10px] text-slate-400">{item.correlation_id}</p>}</div><div className="flex gap-2"><button disabled={busy===item.id} onClick={()=>decide(kind,item.id,"rejected")} className="rounded-xl border border-red-200 px-4 py-2 text-xs font-bold text-red-700">رفض</button><button disabled={busy===item.id} onClick={()=>decide(kind,item.id,"approved")} className="rounded-xl bg-[#0066cc] px-4 py-2 text-xs font-bold text-white">اعتماد وتطبيق</button></div></div></article>)}</div></main>;
}
