"use client";

import { useState } from "react";
import { AlertTriangle, CalendarClock, GitBranch, Pencil, UserPlus, UsersRound, X } from "lucide-react";
import type { CouncilMembership, ReferenceOption, RoleOption, UserOption } from "../model/types";

const field = "h-11 w-full rounded-xl border border-[#d8e3ed] bg-white px-3 text-xs outline-none focus:border-[#0872df] focus:ring-4 focus:ring-[#0872df]/10";

function Shell({ title, description, icon: Icon, danger = false, children, onClose }: { title: string; description: string; icon: typeof AlertTriangle; danger?: boolean; children: React.ReactNode; onClose: () => void }) {
  return <div className="fixed inset-0 z-50 grid place-items-center bg-[#06162d]/55 p-4 backdrop-blur-sm" role="dialog" aria-modal="true"><div className="w-full max-w-lg overflow-hidden rounded-3xl bg-white shadow-[0_28px_80px_rgba(5,24,52,.28)]"><header className="flex items-start gap-3 border-b border-[#e5edf4] p-5"><span className={`grid h-11 w-11 shrink-0 place-items-center rounded-2xl ${danger ? "bg-red-50 text-red-700" : "bg-[#eaf4ff] text-[#0872df]"}`}><Icon size={20} /></span><div><h2 className="text-sm font-black text-[#10233c]">{title}</h2><p className="mt-1 text-[10px] leading-5 text-[#75879b]">{description}</p></div><button type="button" onClick={onClose} className="mr-auto text-[#8292a4]" aria-label="إغلاق"><X size={19} /></button></header>{children}</div></div>;
}

export function ReasonDialog({ title, description, confirmLabel, danger, onClose, onConfirm }: { title: string; description: string; confirmLabel: string; danger?: boolean; onClose: () => void; onConfirm: (reason: string) => Promise<void> }) {
  const [reason, setReason] = useState(""); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  async function submit(e: React.FormEvent) { e.preventDefault(); setSaving(true); setError(""); try { await onConfirm(reason); onClose(); } catch (x) { setError(x instanceof Error ? x.message : "تعذر تنفيذ الإجراء."); } finally { setSaving(false); } }
  return <Shell title={title} description={description} icon={AlertTriangle} danger={danger} onClose={onClose}><form onSubmit={submit}><div className="p-5">{error && <p className="mb-3 rounded-xl bg-red-50 p-3 text-xs font-bold text-red-700">{error}</p>}<label className="text-xs font-black text-[#344861]">سبب الإجراء *</label><textarea required minLength={5} rows={4} value={reason} onChange={(e) => setReason(e.target.value)} className={`${field} mt-2 h-auto py-3`} placeholder="اكتب سبباً واضحاً يظهر في سجل التدقيق..." /></div><Footer saving={saving} onClose={onClose} label={confirmLabel} danger={danger} /></form></Shell>;
}

export function MoveCouncilDialog({ parents, currentId, onClose, onConfirm }: { parents: ReferenceOption[]; currentId: string; onClose: () => void; onConfirm: (parentId: string | null, reason: string) => Promise<void> }) {
  const [parent, setParent] = useState(""); const [reason, setReason] = useState(""); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  async function submit(e: React.FormEvent) { e.preventDefault(); setSaving(true); setError(""); try { await onConfirm(parent || null, reason); onClose(); } catch (x) { setError(x instanceof Error ? x.message : "تعذر نقل المجلس."); } finally { setSaving(false); } }
  return <Shell title="نقل المجلس داخل الهيكل" description="سيتم تحديث مستوى المجلس وجميع المجالس التابعة مع منع العلاقات الدائرية." icon={GitBranch} onClose={onClose}><form onSubmit={submit}><div className="space-y-4 p-5">{error && <p className="rounded-xl bg-red-50 p-3 text-xs font-bold text-red-700">{error}</p>}<label className="block text-xs font-black text-[#344861]">الوحدة الأب الجديدة<select value={parent} onChange={(e) => setParent(e.target.value)} className={`${field} mt-2`}><option value="">جذر الهيكل</option>{parents.filter((p) => p.id !== currentId).map((p) => <option key={p.id} value={p.id}>{p.name_ar}</option>)}</select></label><label className="block text-xs font-black text-[#344861]">سبب النقل *<textarea required minLength={5} rows={3} value={reason} onChange={(e) => setReason(e.target.value)} className={`${field} mt-2 h-auto py-3`} /></label></div><Footer saving={saving} onClose={onClose} label="اعتماد النقل" /></form></Shell>;
}

export function MemberDialog({ users, roles, onClose, onConfirm }: { users: UserOption[]; roles: RoleOption[]; onClose: () => void; onConfirm: (value: { userId: string; roleId: string; title: string; start: string; end: string | null }) => Promise<void> }) {
  const membershipRoles = roles.filter((role) => role.role_scope === "governance_unit" && !["council_chair", "council_rapporteur"].includes(role.code));
  const today = new Date().toISOString().slice(0, 10); const [userId, setUserId] = useState(""); const [roleId, setRoleId] = useState(""); const [title, setTitle] = useState("عضو مجلس"); const [start, setStart] = useState(today); const [end, setEnd] = useState(""); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  async function submit(e: React.FormEvent) { e.preventDefault(); setSaving(true); setError(""); try { await onConfirm({ userId, roleId, title, start, end: end || null }); onClose(); } catch (x) { setError(x instanceof Error ? x.message : "تعذر إضافة العضو."); } finally { setSaving(false); } }
  return <Shell title="إضافة عضو إلى المجلس" description="اختر مستخدماً غير مضاف وحدد فترة عضويته. الرئيس والمقرر يعينان من إجراء القيادة المنفصل." icon={UserPlus} onClose={onClose}><form onSubmit={submit}><div className="grid gap-4 p-5 sm:grid-cols-2">{error && <p className="sm:col-span-2 rounded-xl bg-red-50 p-3 text-xs font-bold text-red-700">{error}</p>}{!users.length && <p className="sm:col-span-2 rounded-xl border border-amber-200 bg-amber-50 p-3 text-xs font-bold text-amber-800">جميع المستخدمين المتاحين أعضاء فعالون في المجلس حالياً.</p>}<Label text="المستخدم"><select required disabled={!users.length} value={userId} onChange={(e) => setUserId(e.target.value)} className={`${field} disabled:bg-slate-100`}><option value="">اختر المستخدم</option>{users.map((u) => <option key={u.id} value={u.id}>{u.full_name_ar} - {u.email}</option>)}</select></Label><Label text="نوع العضوية"><select required disabled={!membershipRoles.length} value={roleId} onChange={(e) => setRoleId(e.target.value)} className={`${field} disabled:bg-slate-100`}><option value="">اختر نوع العضوية</option>{membershipRoles.map((role) => <option key={role.id} value={role.id}>{role.name_ar}</option>)}</select></Label><Label text="المسمى داخل المجلس"><input required value={title} onChange={(e) => setTitle(e.target.value)} className={field} /></Label><Label text="تاريخ البداية"><input required type="date" value={start} onChange={(e) => setStart(e.target.value)} className={field} /></Label><Label text="تاريخ النهاية (اختياري)"><input type="date" min={start} value={end} onChange={(e) => setEnd(e.target.value)} className={field} /></Label></div><Footer saving={saving} onClose={onClose} label="إضافة العضو" disabled={!users.length || !membershipRoles.length} /></form></Shell>;
}

export function LeadershipDialog({ users, members, onClose, onConfirm }: { users: UserOption[]; members: CouncilMembership[]; onClose: () => void; onConfirm: (chair: string, rapporteur: string, date: string, reason: string) => Promise<void> }) {
  const candidates = users.filter((u) => members.some((m) => m.user_id === u.id && m.is_effective)); const today = new Date().toISOString().slice(0, 10); const [chair, setChair] = useState(""); const [rapporteur, setRapporteur] = useState(""); const [date, setDate] = useState(today); const [reason, setReason] = useState(""); const [saving, setSaving] = useState(false); const [error, setError] = useState("");
  async function submit(e: React.FormEvent) { e.preventDefault(); setSaving(true); setError(""); try { await onConfirm(chair, rapporteur, date, reason); onClose(); } catch (x) { setError(x instanceof Error ? x.message : "تعذر تعيين القيادة."); } finally { setSaving(false); } }
  return <Shell title="تعيين قيادة المجلس" description="لا يظهر إلا الأعضاء الفعالون. يطبق تعيين الرئيس والمقرر في معاملة ذرية واحدة." icon={UsersRound} onClose={onClose}><form onSubmit={submit}><div className="space-y-4 p-5">{error && <p className="rounded-xl bg-red-50 p-3 text-xs font-bold text-red-700">{error}</p>}{!candidates.length && <p className="rounded-xl border border-amber-200 bg-amber-50 p-3 text-xs font-bold text-amber-800">أضف أعضاء فعالين أولاً قبل تعيين القيادة.</p>}<Label text="رئيس المجلس"><select required value={chair} onChange={(e) => setChair(e.target.value)} className={field}><option value="">اختر الرئيس</option>{candidates.map((u) => <option key={u.id} value={u.id}>{u.full_name_ar}</option>)}</select></Label><Label text="مقرر المجلس"><select required value={rapporteur} onChange={(e) => setRapporteur(e.target.value)} className={field}><option value="">اختر المقرر</option>{candidates.map((u) => <option key={u.id} value={u.id}>{u.full_name_ar}</option>)}</select></Label><Label text="تاريخ السريان"><input required type="date" value={date} onChange={(e) => setDate(e.target.value)} className={field} /></Label><Label text="سبب التعيين"><textarea required minLength={5} rows={3} value={reason} onChange={(e) => setReason(e.target.value)} className={`${field} h-auto py-3`} /></Label></div><Footer saving={saving} onClose={onClose} label="اعتماد القيادة" /></form></Shell>;
}

export function EditMembershipDialog({ membership, onClose, onConfirm }: { membership: CouncilMembership; onClose: () => void; onConfirm: (value: { title: string; start: string; end: string | null }) => Promise<void> }) {
  const [title, setTitle] = useState(membership.membership_title ?? "");
  const [start, setStart] = useState(membership.start_date);
  const [end, setEnd] = useState(membership.end_date ?? "");
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState("");
  async function submit(e: React.FormEvent) { e.preventDefault(); setSaving(true); setError(""); try { await onConfirm({ title, start, end: end || null }); onClose(); } catch (x) { setError(x instanceof Error ? x.message : "تعذر تعديل العضوية."); } finally { setSaving(false); } }
  return <Shell title="تعديل بيانات العضوية" description={`تحديث المسمى وفترة عضوية ${membership.full_name_ar} دون تغيير المستخدم أو الدور.`} icon={Pencil} onClose={onClose}><form onSubmit={submit}><div className="space-y-4 p-5">{error && <p className="rounded-xl bg-red-50 p-3 text-xs font-bold text-red-700">{error}</p>}<div className="rounded-xl border border-[#e2eaf2] bg-[#f8fbfe] p-3"><strong className="block text-xs text-[#223952]">{membership.full_name_ar}</strong><span className="mt-1 block text-[10px] text-[#75879b]">{membership.role_name_ar}</span></div><Label text="المسمى داخل المجلس"><input required value={title} onChange={(e) => setTitle(e.target.value)} className={field} /></Label><div className="grid gap-4 sm:grid-cols-2"><Label text="تاريخ البداية"><input required type="date" value={start} onChange={(e) => setStart(e.target.value)} className={field} /></Label><Label text="تاريخ النهاية (اختياري)"><input type="date" min={start} value={end} onChange={(e) => setEnd(e.target.value)} className={field} /></Label></div></div><Footer saving={saving} onClose={onClose} label="حفظ العضوية" /></form></Shell>;
}

export function EndMembershipDialog({ membership, onClose, onConfirm }: { membership: CouncilMembership; onClose: () => void; onConfirm: (endDate: string, reason: string) => Promise<void> }) {
  const today = new Date().toISOString().slice(0, 10);
  const [endDate, setEndDate] = useState(today < membership.start_date ? membership.start_date : today);
  const [reason, setReason] = useState("");
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState("");
  async function submit(e: React.FormEvent) { e.preventDefault(); setSaving(true); setError(""); try { await onConfirm(endDate, reason); onClose(); } catch (x) { setError(x instanceof Error ? x.message : "تعذر إنهاء العضوية."); } finally { setSaving(false); } }
  return <Shell title="إنهاء عضوية المجلس" description={`سينتهي وصول ${membership.full_name_ar} المرتبط بهذه العضوية في التاريخ المحدد، مع الاحتفاظ بالسجل.`} icon={CalendarClock} danger onClose={onClose}><form onSubmit={submit}><div className="space-y-4 p-5">{error && <p className="rounded-xl bg-red-50 p-3 text-xs font-bold text-red-700">{error}</p>}<Label text="تاريخ الإنهاء"><input required type="date" min={membership.start_date} value={endDate} onChange={(e) => setEndDate(e.target.value)} className={field} /></Label><Label text="سبب الإنهاء"><textarea required minLength={5} rows={3} value={reason} onChange={(e) => setReason(e.target.value)} className={`${field} h-auto py-3`} placeholder="اكتب سبباً واضحاً لسجل التدقيق..." /></Label></div><Footer saving={saving} onClose={onClose} label="إنهاء العضوية" danger /></form></Shell>;
}

function Label({ text, children }: { text: string; children: React.ReactNode }) { return <label className="block text-xs font-black text-[#344861]"><span className="mb-2 block">{text}</span>{children}</label>; }
function Footer({ saving, onClose, label, danger, disabled = false }: { saving: boolean; onClose: () => void; label: string; danger?: boolean; disabled?: boolean }) { return <footer className="flex justify-end gap-3 border-t border-[#e5edf4] bg-[#fbfdff] px-5 py-4"><button type="button" onClick={onClose} className="h-10 rounded-xl border border-[#d8e3ed] px-4 text-xs font-bold text-[#52647a]">إلغاء</button><button disabled={saving || disabled} className={`h-10 rounded-xl px-5 text-xs font-black text-white disabled:cursor-not-allowed disabled:opacity-60 ${danger ? "bg-red-700" : "bg-[#0872df]"}`}>{saving ? "جارٍ التنفيذ..." : label}</button></footer>; }
